data:
  dataset: imagenet
  root: ""
  num_workers: 12
  pin_memory: 1
  prefetch_factor: 4
logging:
  folder: ./tmp/
lr:
  lr: 0.2125
  lr_schedule_type: cyclic
model:
  arch: resnet50
  prefix_mask_prob: 0.0
  prefix_mask_scale: none
resolution:
  end_ramp: 34
  max_res: 192
  min_res: 160
  start_ramp: 29
training:
  batch_size: 512
  bn_wd: 0
  epochs: 40
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  lr_tta: 1
  resolution: 256
