data:
  dataset: cifar100
  root: ""
  num_workers: 4
  pin_memory: 1
  prefetch_factor: 4
logging:
  folder: ./tmp/
lr:
  lr: 0.1
  lr_schedule_type: cyclic
model:
  arch: resnet50
  bor_mrl: 0
  bor_block_mrl: 0
  cascade_stop_gradient_mrl: 0
  bor_mode: orthogonal
  bor_orthogonal_map: matrix_exp
  bor_use_trivialization: 1
  bor_stop_gradient: 0
  bor_residual_orthogonal: 0
  bor_residual_alpha_init: -3.0
  cascade_stop_gradient: -1
resolution:
  end_ramp: 0
  max_res: 32
  min_res: 32
  start_ramp: 0
training:
  batch_size: 256
  bn_wd: 0
  deterministic: 1
  epochs: 40
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  seed: 0
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  batch_size: 256
  lr_tta: 1
  resolution: 32
